config:
  partial_parse: true
insurance_project:
  target: prod
  outputs:
    prod:
      type: fabric
      driver: "ODBC Driver 18 for SQL Server"
      server: ${DBT-FABRIC-SERVER}
      port: 1433
      database: "wh_insurance"
      method: spark
      schema: silver
      authentication: ServicePrincipal
      tenant_id: ${DBT-FABRIC-TENANT_ID}
      client_id: ${DBT-FABRIC-CLIENT_ID}
      client_secret: ${DBT-FABRIC-CLIENT-SECRET}
      threads: 4
      timeout: 300
      retries: 1

    dev:
      type: fabric
      driver: "ODBC Driver 18 for SQL Server"
      server: ${DBT-FABRIC-SERVER}
      port: 1433
      database: "wh_insurance"
      method: spark
      schema: silver
      authentication: ServicePrincipal
      tenant_id: ${DBT-FABRIC-TENANT-ID}
      client_id: ${DBT-FABRIC-CLIENT_ID}
      client_secret: ${DBT-FABRIC-CLIENT-SECRET}
      threads: 4
      timeout: 300
      retries: 1
