models:
  - name: gt_ins_claims
    description: This is the cleaned claims dataset for consumption by reports and analyst
    columns:
      - name: claim_id
        description: Identifier for claims
        tests:
          - not_null
          - unique
      - name: policy_id
        description: Policy Id of the claim foreign key of policies table
      - name: claim_date
        description: date claim was recorded
        tests:
          - not_null
      - name: claim_amount
        description: The dollar amount of the claim
        tests:
          - less_than_zero
      - name: status
        description: Status of a claim - Approved, Pending, Rejected
      - name: gender
        description: Gender of Claimant - Male or Female
      - name: deductible
        description: Money paying out of pocket before insurance pays
      - name: claim_reason
        description: Reason for the claim - Theft, fire
      - name: is_fraud
        description: Whether claim is fraudulent or not
      - name: Zip_Code
        description: Geographic area claim was made
